name: PubMed_AI_Scraper
on:
  schedule:
    - cron: '0 0 * * 1' # 每週一 00:00 UTC 執行
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run logic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_B4_API_KEY }}
          # EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          # TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
        run: python scraper.py
